### ISSUE TITLE
error when using EventBus.send

### ISSUE THREAD

**Issue by skyboys22** [jmusacchio/vertxbus#2]
Hello,

i'm trying vert.x of meteor, and i'm getting error in **EventBus.Send**: 

```
if (Meteor.isServer) {
  Meteor.startup(function () {
    EventBus = new Vertx.EventBus("http://localhost:8080/");
    EventBus.onopen = function() {
      EventBus.registerHandler("vertx-news-feed", function(error, msg) {
        if(error === null) console.log(msg.body);
      })
    }
  EventBus.send('meteor-news-feed', message, function(error, reply) {
      if(error === null) console.log(reply.body);
    });
}
});
```

anyone can help me to resolve this? thank you :)

**Comment by jmusacchio** [comment]
Can you supply the Vertx code? could be possible that you are missing eventbus path on the URL? Depends on how you configured your router....

EventBus = new Vertx.EventBus("http://localhost:8080/**eventbus**");

router.route("/**eventbus**/*").handler(SockJSHandler.create(vertx).bridge(options));

Also if you can provide the error you got, would be helpful. Be aware of configuring inbound and outbound addresses on Vertx.

**Comment by skyboys22** [comment]
i moved the function in client and it's resolved, maybe the probleme because it was inside meteor.startup? now i'm getting connection refused
`jmusacchio_vertxbus.js:1712 GET http://localhost:8080/coursierPrive/info?t=1458059324579 net::ERR_CONNECTION_REFUSED`
, any idea ? thank you very much for your reply

**Comment by jmusacchio** [comment]
The function call should work in both meteor sides (Server or client). 
The problem with the above code you supplied is that the end round bracket ")" should be placed before the last curly bracket "}"

```
if (Meteor.isServer) {
    Meteor.startup(function () {
        EventBus = new Vertx.EventBus("http://localhost:8080/");
        EventBus.onopen = function() {
            EventBus.registerHandler("vertx-news-feed", function(error, msg) {
                if(error === null) console.log(msg.body);
            })
        }
        EventBus.send('meteor-news-feed', message, function(error, reply) {
            if(error === null) console.log(reply.body);
        });
    })
};

```

It seems that you router should be configured to listen to **coursierPrive** path:

router.route("/**coursierPrive**/*").handler(SockJSHandler.create(vertx).bridge(options));

**Comment by jmusacchio** [comment]
Coud you fix the problem so I can close this issue?

**Comment by jmusacchio** [comment]
Closing issue is not a package problem.

**Comment by skyboys22** [comment]
sorry i wasn't there to answer, i did what you told me but i still have an error.

after creating socket, i got exception in route; noSuchMethodError !!

**Comment by jmusacchio** [comment]
Please send me some code examples (meteor + vertx) by email (juan.musacchio@gmail.com) so I can help you out otherwise is impossible.
